spring:
  cloud:
    stream:
      bindings:
        subscribe: # @See LogSubscribeChannel.SUBSCRIBE
          destination: topic-log
      kafka:
        binder: #指定kafka broker和zookeeper nodes
          brokers:
            - 192.168.1.90:9000
            - 192.168.1.90:9001
            - 192.168.1.90:9002
          zkNodes: 192.168.1.90:2181
server:
  port: 10002